<<: !include "hpack/lib.yaml"

name: loot-base

library:
  <<: *lib-common

  dependencies:
    - lens
    - tagged
    - template-haskell
    - text

tests:
  loot-base-test:
    <<: *test-common

    dependencies:
      - tasty
      - tasty-discover
