<<: !include "hpack/lib.yaml"

name: loot-base

library:
  <<: *lib-common

  dependencies:
    - microlens
    - safe-exceptions
    - tagged

tests:
  loot-base-test:
    <<: *test-common

    dependencies:
      - tasty
      - tasty-discover
