<<: !include "../base/hpack/lib.yaml"

name: loot-config

library:
  <<: *lib-common

  dependencies:
    - aeson
    - aeson-better-errors
    - data-default
    - microlens
    - validation
    - vinyl

tests:
  loot-base-test:
    <<: *test-common

    dependencies:
      - loot-config

      - hedgehog
      - tasty
      - tasty-discover
      - tasty-hedgehog
      - tasty-hunit

      - aeson
