name: loot-demo
default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: lib

  dependencies:
    - base
    - universum
    - loot-config
    - loot-log

executables:
  loot-demo:
    source-dirs: app
    main: Main.hs

    dependencies:
      - base
      - universum
      - loot-demo
      - loot-log
      - loot-demo

      - caps
      - fmt
      - loot-config
      - yaml

ghc-options:
  - -Wall
