<<: !include "../base/hpack/lib.yaml"

name: loot-network

library:
  <<: *lib-common

  dependencies:
    - async
    - bytestring
    - containers
    - dependent-map
    - dependent-sum
    - lens
    - mtl
    - network
    - serialise
    - singletons
    - stm
    - random
    - reflection
    - tagged
    - unordered-containers
    - zeromq4-haskell

tests:
  loot-base-test:
    <<: *test-common

    dependencies:
      - tasty
      - tasty-discover
