<<: !include "../base/hpack/lib.yaml"

name: loot-crio

library:
  <<: *lib-common

  dependencies:
    - loot-base
    - loot-prelude
    - HList
    - mtl
    - safe-exceptions
    - singletons
    - text

    # caps:
    - exceptions
    - template-haskell
    - transformers
    - typerep-map

tests:
  loot-log-test:
    <<: *test-common

    dependencies:
      - loot-crio

      - hedgehog
      - tasty
      - tasty-discover
      - tasty-hedgehog
      - tasty-hunit
